
function ekarriGaldera(){
	//......1
	var galdesorta = 
	{"galderak":	   
	[{"galdera":"ERLATIBOA" },
	//--------------1
	{"galdera":"No estoy de acuerdo con lo que has dicho.", 
	"auke1":"Ez nago ados esan duzunarekin.","auke2":"Ez nago ados esandakoarekin.","auke3":"Ez nago ados esanarekin.",
	"zuzena":"auke1",
	"eranfb1":"Bai, hori da erantzun zuzena:\n-Ez nago ados esan duzunarekin.-.",
	"eranfb2":"Ez da zuzena.\n-Ez nago ados esan duzunarekin.- da zuzena.",
	"eranfb3":"Ez da zuzena.\n-Ez nago ados esan duzunarekin.- da zuzena."	},
		//......2
	{"galdera":"El perro que ladra mucho no muerde.",
	"auke1":"Zakurrak zaunka asko zeren ez du horzka egiten.","auke2":"Zakurrak zeinak zaunka asko egiten du, ez du horzka egiten.","auke3":"Zaunka asko egiten duen zakurrak ez du horzkarik egiten.",
	"zuzena":"auke3",
	"eranfb1":"Ez da zuzena.\n-Zaunka asko egiten duen zakurrak ez du horzkarik egiten.- da zuzena.",
	"eranfb2":"Ez da zuzena.\n-Zaunka asko egiten duen zakurrak ez du horzkarik egiten.- da zuzena.",
	"eranfb3":"Bai, hori da erantzun zuzena:\n-Zaunka asko egiten duen zakurrak ez du horzkarik egiten.-"},
		//......3
	{"galdera":"He traido este regalo para el que cumple años.",
	"auke1":"Ekarri dut opari hau harentzat urteak betetzen du.","auke2":"Opari hau urteak betetzen duenarentzat ekarri dut.","auke3":"Urteak betetzen opari hau ekarri dut.",
	"zuzena":"auke2",
	"eranfb1":"Ez da zuzena.\n-Opari hau urteak betetzen duenarentzat ekarri dut.- da zuzena.",
	"eranfb2":"Bai, hori da erantzun zuzena:\n-Opari hau urteak betetzen duenarentzat ekarri dut.-",
	"eranfb3":"Ez da zuzena.\n-Opari hau urteak betetzen duenarentzat ekarri dut.- da zuzena."},
		//......4
	{"galdera":"Pelearemos el día que quieras, en el sitio que quieras.",
	"auke1":"Borrokan egingo dugu egunean nahi duzuna, tokia nahi duzuna.","auke2":"Borrokan egingo dugu egunean eta tokian nahi duzunean.","auke3":"Nahi duzun egunean, nahi duzun tokian egingo dugu borrokan.",
	"zuzena":"auke3",
	"eranfb1":"Ez da zuzena.\n–Nahi duzun egunean, nahi duzun tokian egingo dugu borrokan.- da zuzena.",
	"eranfb2":"Ez da zuzena.\n–Nahi duzun egunean, nahi duzun tokian egingo dugu borrokan.- da zuzena.",
	"eranfb3":"Bai, hori da erantzun zuzena:\n-Nahi duzun egunean, nahi duzun tokian egingo dugu borrokan.-"},
		//......5
	{"galdera":"No me importa pagar por los libros que son buenos.",
	"auke1":"Ez dit garrantzia ordaintzea liburu onak.","auke2":"Ez dit axola onak diren liburuengatik ordaintzea.","auke3":"Ez dit axola oradintzea liburu onak.",
	"zuzena":"auke2",
	"eranfb1":"Ez da zuzena.\n–Ez dit axola onak diren liburuengatik ordaintzea.-",
	"eranfb2":" Bai, hori da erantzun zuzena:\n-Ez dit axola onak diren liburuengatik ordaintzea.-",
	"eranfb3":" Ez da zuzena.\n–Ez dit axola onak diren liburuengatik ordaintzea.-"},
		//......6
	{"galdera":"Al que le gusta comer también le gusta beber.",
	"auke1":"Jatea gustatzen zaionari edatea ere gustatzen zaio.","auke2":"Gustatzen zaionari jatea ere gustatzen zaio edatea.","auke3":"Gustatzen zaiona jateari edatea ere gustatzen zaio.",
	"zuzena":"auke1",
	"eranfb1":"Bai, hori da erantzun zuzena:\nJatea gustatzen zaionari edatea ere gustatzen zaio.- ",
	"eranfb2":"Ez da zuzena.\n–Jatea gustatzen zaionari edatea ere gustatzen zaio.- da zuzena.",
	"eranfb3":"Ez da zuzena.\n–Jatea gustatzen zaionari edatea ere gustatzen zaio.- da zuzena. "},
	//......7
	{"galdera":"El que a hierro mata a hierro muere.",
	"auke1":"Bera zeina burdinaz hiltzen du, burdinaz hiltzen da.","auke2":"Burdinaz hiltzen duena burdinaz hiltzen da.","auke3":"Berak burdinaz hiltzen du, bera burdinaz hiltzen da.",
	"zuzena":"auke2",
	"eranfb1":"Ez da zuzena.\n–Burdinaz hiltzen duena burdinaz hiltzen da.-",
	"eranfb2":"Bai, hori da erantzun zuzena:\n-Burdinaz hiltzen duena burdinaz hiltzen da.-.",
	"eranfb3":"Ez da zuzena.\n–Burdinaz hiltzen duena burdinaz hiltzen da.-"},
	//......8
	{"galdera":"Quisiera hacerte unas preguntas sobre algunos temas que me interesan mucho.",
	"auke1":"Asko interesatzen zaizkidan hainbat gairi buruz galdera batzuk egin nahi nizkizuke.","auke2":"Nahi nuke galdera batzuk egin gainean hainbat gai zeintzuk asko interesatzen zaizkit.","auke3":"Nahi nizuke galderak egin interesatzen zaizkidan gai askori buruz.",
	"zuzena":"auke1",
	"eranfb1":"Bai, hori da erantzun zuzena:\n-Asko interesatzen zaizkidan hainbat gairi buruz galdera batzuk egin nahi nizkizuke.-.",
	"eranfb2":"Ez da zuzena.\n–Asko interesatzen zaizkidan hainbat gairi buruz galdera batzuk egin nahi nizkizuke.- da zuzena.",
	"eranfb3":"Ez da zuzena.\n–Asko interesatzen zaizkidan hainbat gairi buruz galdera batzuk egin nahi nizkizuke.- da zuzena."},
		//......9
	{"galdera":"No debemos lamentarnos de lo que pudimos hacer y no hicimos.",
	"auke1":"Ez behar dugu damutu egin ahal dugu eta ez dugu egin.","auke2":"Ez dugu damutu behar egin ahal izan genuena ez dugulako egin.","auke3":"Ez dugu kexatu behar egin ahal izan eta egin ez genuenaz.",
	"zuzena":"auke3",
	"eranfb1":"Ez da zuzena.\n–Ez dugu kexatu behar egin ahal izan eta egin ez genuenaz.- da zuzena.",
	"eranfb2":"Ez da zuzena.\n–Ez dugu kexatu behar egin ahal izan eta egin ez genuenaz.- da zuzena.",
	"eranfb3":"Bai, hori da erantzun zuzena:\n-Ez dugu kexatu behar egin ahal izan eta egin ez genuenaz.-."},
		//......10
	{"galdera":"La gente con la que vivo no me gusta.",
	"auke1":"Jendea ni bizi naizena ez zait gustatzen.","auke2":"Nirekin bizi den jendea ez da nire gustukoa.","auke3":"Jendea zeinarekin ni bizi naizen ez da nire guztukoa.",
	"zuzena":"auke2",
	"eranfb1":"Ez da zuzena.\n–Nirekin bizi den jendea ez da nire gustukoa.- da zuzena.",
	"eranfb2":"Bai, hori da erantzun zuzena:\n-Nirekin bizi den jendea ez da nire gustukoa.-.",
	"eranfb3":"Ez da zuzena.\n–Nirekin bizi den jendea ez da nire gustukoa.- da zuzena. "},
	//......11
	{"galdera":"El libro del que me has hablado está agotado.",
	"auke1":"Liburua hari buruz zuk hitz egin didazu, bukatua dago.","auke2":"Liburuari buruz zuk hitz egin didazu, amaitua dago.","auke3":"Aipatu didazun liburua ahitua dago. ",
	"zuzena":"auke3",
	"eranfb1":"Ez da zuzena.\n–Aipatu didazun liburua ahitua dago.- da zuzena.",
	"eranfb2":"Ez da zuzena.\n–Aipatu didazun liburua ahitua dago.- da zuzena.",
	"eranfb3":"Bai, hori da erantzun zuzena:\n-Aipatu didazun liburua ahitua dago."},
		//......12
	{"galdera":"El barrio en el que vivo está lleno de ratas.",
	"auke1":"Ni bizi naizen auzoa arratoiz beteta dago.","auke2":"Auzoa non ni bizi naizen dago beteta arratoiak.","auke3":"Auzoa ni bizi naiz arratoiz beteta dago.",
	"zuzena":"auke1",
	"eranfb1":"Bai, hori da erantzun zuzena:\n-Ni bizi naizen auzoa arratoiz beteta dago.",
	"eranfb2":"Ez da zuzena.\n–Ni bizi naizen auzoa arratoiz beteta dago.- da zuzena.",
	"eranfb3":"Ez da zuzena.\n–Ni bizi naizen auzoa arratoiz beteta dago.- da zuzena."},
		//......13
	{"galdera":"Los irakasles que viven bien no se quejan nunca.",
	"auke1":"irakasleak ez dira inoiz kexatzen, ongi bizi direlako.","auke2":"Ondo bizi diren irakasleak ez dira sekula kexatzen.","auke3":"Ongi biz direnez, irakasleak ez dira kexatzen inoiz.",
	"zuzena":"auke2",
	"eranfb1":"Ez da zuzena.\n–Ondo bizi diren irakasleak ez dira sekula kexatzen.- da zuzena.",
	"eranfb2":"Bai, hori da erantzun zuzena:\n-Ondo bizi diren irakasleak ez dira sekula kexatzen.",
	"eranfb3":"Ez da zuzena.\n–Ondo bizi diren irakasleak ez dira sekula kexatzen.- da zuzena."},
		//......14
	{"galdera":"Los irakasles, que viven bien, no deberían quejarse nunca.",
	"auke1":"Irakasleak, zein ondo bizi baitira, ez lirateke sekula kexatu behar.","auke2":"Irakasleak, zeinak ongi bizi dira, ez dezakete behar kexatu zekula. ","auke3":"Irakasleak, ongi bizi direnak, ez dezatela sekula kexatu.",
	"zuzena":"auke1",
	"eranfb1":"Bai, hori da erantzun zuzena:\n-Irakasleak, zein ondo bizi baitira, ez lirateke sekula kexatu behar.-",
	"eranfb2":"Ez da zuzena.\n–Irakasleak, zein ondo bizi baitira, ez lirateke sekula kexatu behar.- da zuzena.",
	"eranfb3":"Ez da zuzena.\n–Irakasleak, zein ondo bizi baitira, ez lirateke sekula kexatu behar.- da zuzena."},
		//......15
	{"galdera":"¿Quién es ese imbécil que no te deja en paz?",
	"auke1":"Zein da ergel hori zeren ez dizu uzten bakean?","auke2":"Nor da hori ergela zeinak ez dizu uzten bakean?","auke3":"Zein da bakean uzten ez dizun ergel hori?",
	"zuzena":"auke3",
	"eranfb1":"Ez da zuzena.\n–Zein da bakean uzten ez dizun ergel hori?- da zuzena.",
	"eranfb2":"Ez da zuzena.\n–Zein da bakean uzten ez dizun ergel hori?- da zuzena.",
	"eranfb3":"Bai, hori da erantzun zuzena:\n-Zein da bakean uzten ez dizun ergel hori?"},
		//......16
	{"galdera":"Los ladrones a los que detuvieron ayer pertenecen a un grupo de carteristas. ",
	"auke1":"Lapurrak atxilotu zituzten atzo, talde karterista bat dira.","auke2":"Lapurrak atzo atxilotu zituzten karterista taldeko partaideak dira.","auke3":"Atzo atxilotu zituzten lapurrak karterista talde batekoak ziren.",
	"zuzena":"auke3",
	"eranfb1":"Ez da zuzena.\n–Atzo atxilotu zituzten lapurrak karterista talde batekoak ziren.- da zuzena.",
	"eranfb2":"Ez da zuzena.\n–Atzo atxilotu zituzten lapurrak karterista talde batekoak ziren.- da zuzena.",
	"eranfb3":"Bai, hori da erantzun zuzena:\n-Atzo atxilotu zituzten lapurrak karterista talde batekoak ziren.-"},
		//......17
	{"galdera":"La casa en la que había alarma no sufrió ningún desperfecto.",
	"auke1":"Etxea non alarma bat zegoen ez zuen nozitu batere apurketarik.","auke2":"Alarma zeukan etxeak ez zuen kalterik jasan.","auke3":"Etxeak, zeinak alarma zeukan, desperfekturik gabe geratu zen.",
	"zuzena":"auke2",
	"eranfb1":"Ez da zuzena.\n–Alarma zeukan etxeak ez zuen kalterik jasan.- da zuzena.",
	"eranfb2":"Bai, hori da erantzun zuzena:\n-Alarma zeukan etxeak ez zuen kalterik jasan.-.",
	"eranfb3":"Ez da zuzena.\n–Alarma zeukan etxeak ez zuen kalterik jasan.- da zuzena."},
	//......18
	{"galdera":"El hombre, que estaba borracho, se portó muy mal conmigo.",
	"auke1":"Gizona, mozkorturik zegoena, oso txarto portatu zen nirekin.","auke2":"Gizona, zein mozkorturik baitzegoen, oso gaizki portatu zen nirekin.","auke3":"Gizona, oso mozkorturik zegoen, gaizki portatu zen oso nirekin.",
	"zuzena":"auke2",
	"eranfb1":"Ez da zuzena.\n–Gizona, zein mozkorturik baitzegoen, oso gaizki portatu zen nirekin.- da zuzena.",
	"eranfb2":"Bai, hori da erantzun zuzena:\n-Gizona, zein mozkorturik baitzegoen, oso gaizki portatu zen nirekin.",
	"eranfb3":"Ez da zuzena.\n–Gizona, zein mozkorturik baitzegoen, oso gaizki portatu zen nirekin.- da zuzena."},
		//......19
	{"galdera":"Todas las veces que te he llamado por teléfono daba comunicando.",
	"auke1":"Guzti aldietan zein deitu baitzaitut telefonoz komunikatzen eman du.","auke2":"Telefonoz deitu dizudan guztietan komunikatzen ematen zuen.","auke3":"Aldi guztietan telefonoz deitu eta komunikatzen ematen zuen.",
	"zuzena":"auke2",
	"eranfb1":"Ez da zuzena.\n–Telefonoz deitu dizudan guztietan komunikatzen ematen zuen.- da zuzena.",
	"eranfb2":"Bai, hori da erantzun zuzena:\n-Telefonoz deitu dizudan guztietan komunikatzen ematen zuen.-",
	"eranfb3":"Ez da zuzena.\n–Telefonoz deitu dizudan guztietan komunikatzen ematen zuen.-"},
		//......20
	{"galdera":"El Quijote, que es la obra cumbre de la literatura castellana, no es un libro muy leido hoy en día.",
	"auke1":"Kixotea, zeina obra gailurra da gaztelako literaturan, ez dago oso irakurri gaur egun.","auke2":"Kixotea, zeina espainiar literaturako obrarik naguziena baita, ez da oso liburu irakurria gaur egun. ","auke3":"Kixote, dela gaztelako obra gailurra, ez da oso irakurria gaur egun.",
	"zuzena":"auke2",
	"eranfb1":"Ez da zuzena.\n–Kixotea, zeina espainiar literaturako obrarik naguziena baita, ez da oso liburu irakurria gaur egun. - da zuzena.",
	"eranfb2":"Bai, hori da erantzun zuzena:\n–Kixotea, zeina espainiar literaturako obrarik naguziena baita, ez da oso liburu irakurria gaur egun.-",
	"eranfb3":"Ez da zuzena.\n–Kixotea, zeina espainiar literaturako obrarik naguziena baita, ez da oso liburu irakurria gaur egun. -"},
		//......21
	{"galdera":"El dueño de la taberna en la que habéis entrado antes tiene fama de chivato.",
	"auke1":"Jabeak tabernako non lehen sartu zareten txibato fama dauka.","auke2":"Lehen sartu zareten tabernako jabeak txibato fama du.","auke3":"Jabea tabernakoak txibatoa fama dauka, lehen sartu zarete. ",
	"zuzena":"auke2",
	"eranfb1":"Ez da zuzena.\n–Lehen sartu zareten tabernako jabeak txibato fama du.- da zuzena.",
	"eranfb2":"Bai, hori da erantzun zuzena: \n–Lehen sartu zareten tabernako jabeak txibato fama du.-.",
	"eranfb3":"Ez da zuzena.\n–Lehen sartu zareten tabernako jabeak txibato fama du.- da zuzena."},
		//......22
	{"galdera":"Que levanten el dedo todos los que han hecho los deberes.",
	"auke1":"Altxa behatza guztiek etxerako lanak egindakoak.","auke2":"Altxa dezatela behatza eskolako lanak egin dituzten guztiek.","auke3":"Altxa behatza eskolako lanak egin dituzten guztiek.",
	"zuzena":"auke2",
	"eranfb1":"Ez da zuzena.\n–Altxa dezatela behatza eskolako lanak egin dituzten guztiek.- da zuzena.",
	"eranfb2":"Bai, hori da erantzun zuzena: \n-Altxa dezatela behatza eskolako lanak egin dituzten guztiek.-",
	"eranfb3":"Ez da zuzena.\n–Altxa dezatela behatza eskolako lanak egin dituzten guztiek.- da zuzena."},
		//......23
	{"galdera":"El muy burro me dio una puñalada en las costillas cuya marca todavía la llevo encima.",
	"auke1":"Astakirten hark saihetsetan eman zidan labankadaren arrastoa oraindik ere aldean daukat.","auke2":"Astakirtenak saihetsetan eman zidan labankadaren arrastoa gainean daukat.","auke3":"Saihetsetan astakirtenak eman zidan labankada eta haren arrastoa oraindik aldean daukat.",
	"zuzena":"auke1",
	"eranfb1":"Bai, hori da erantzun zuzena:\n-Astakirten hark saihetsetan eman zidan labankadaren arrastoa oraindik ere aldean daukat.-. ",
	"eranfb2":"Ez da zuzena.\n-Astakirten hark saihetsetan eman zidan labankadaren arrastoa oraindik ere aldean daukat.- da zuzena.",
	"eranfb3":"Ez da zuzena.\n-Astakirten hark saihetsetan eman zidan labankadaren arrastoa oraindik ere aldean daukat.- da zuzena."},
		//......24
	{"galdera":"Se fue a Gasteiz que es donde se reunía la comisión de derechos humanos.",
	"auke1":"Gasteiza joan zen, non da biltzen zela Giza Eskubideen batzordea.","auke2":"Gasteiza joan zen, non da non biltzen zen Giza Eskubideen batzordea.","auke3":"Gasteiza joan zen, non biltzen zen Giza Eskubideen batzordea.",
	"zuzena":"auke3",
	"eranfb1":"Ez da zuzena.\n-Gasteiza joan zen, non biltzen zen Giza Eskubideen batzordea.- da zuzena.",
	"eranfb2":"Ez da zuzena.\n-Gasteiza joan zen, non biltzen zen Giza Eskubideen batzordea.- da zuzena.",
	"eranfb3":"Bai, hori da erantzun zuzena:\n-Gasteiz joan zen, non biltzen zen Giza Eskubideen batzordea."},
		//......25
	{"galdera":"En medio de la plaza había un cartel que decía 'Gora Euskadi Askatuta'",
	"auke1":"Erdian plazan kartel handi bat zegoela, zeinetan 'Gora Euskadi Askatuta' jartzen zuen.","auke2":"Erdiaren plazan kartel bat zegoen, zeinetan 'Gora Euskadi Askatuta' jartzen zuen.","auke3":"Plazaren erdian kartel handi bat zegoen, zeinetan 'Gora Euskadi Askatuta' jartzen zuen.",
	"zuzena":"auke3",
	"eranfb1":"Ez da zuzena. \n-Plazaren erdian kartel handi bat zegoen, zeinetan 'Gora Euskadi Askatuta' jartzen zuen.- da zuzena. ",
	"eranfb2":"Ez da zuzena. \n-Plazaren erdian kartel handi bat zegoen, zeinetan 'Gora Euskadi Askatuta' jartzen zuen.- da zuzena. ",
	"eranfb3":"Bai, hori da erantzun zuzena:\n-Plazaren erdian kartel handi bat zegoen, zeinetan 'Gora Euskadi Askatuta' jartzen zuen.-."},
		//......26
	{"galdera":"Limpia esos vasos que están sucios.",
	"auke1":"Zikin daude edalontziak garbi itzazu.","auke2":"Zikin dauden edalontzi horiek garbi itzazu.","auke3":"Edalontzi zikin horiek garbi itzazu.",
	"zuzena":"auke2",
	"eranfb1":"Ez da zuzena.\n-Zikin dauden edalontzi horiek garbi itzazu.- da zuzena.",
	"eranfb2":"Bai, hori da erantzun zuzena:\n-Zikin dauden edalontzi horiek garbi itzazu.-",
	"eranfb3":"Ez da zuzena.\n-Zikin dauden edalontzi horiek garbi itzazu.- da zuzena."},
			//......27
	{"galdera":"Los alumnos cuyos padres son analfabetos, tienen más problemas para desarrollar su inteligencia.",
	"auke1":"Alfabetatu gabeko gurasoak arazo gehiago izaten dituzte beren adimena garatzeko.","auke2":"Guraso alfabetatu gabeak dituzten ikasleak arazo gehiago izaten dituzte beren adimena garatzeko.","auke3":"Guraso alfabetatu gabeko ikasleak arazo gehiago izaten dituzte beren adimena garatzeko.",
	"zuzena":"auke2",
	"eranfb1":"Ez da zuzena.\n-Guraso alfabetatu gabeak dituzten ikasleak arazo gehiago izaten dituzte beren adimena garatzeko.- da zuzena.",
	"eranfb2":"Bai, hori da erantzun zuzena: \n-Guraso alfabetatu gabeak dituzten ikasleak arazo gehiago izaten dituzte beren adimena garatzeko.-",
	"eranfb3":"Ez da zuzena.\n-Guraso alfabetatu gabeak dituzten ikasleak arazo gehiago izaten dituzte beren adimena garatzeko.- da zuzena."},
		//......23
	{"galdera":"Hace mucho vivía en Donostia un hombre, que se llamaba Epifanio, que solía dormir en la playa de la Concha.",
	"auke1":"Aspaldi Donostian Kontxako hondartzan lo egiten zuen Epifanio izeneko gizon bat bizi zen.","auke2":"Aspaldi Donostian bizi zen Epifanio izeneko gizon bat, zeinak Kontxako hondartzan lo egiten zuen.","auke3":"Aspaldi Donostian Kontxako hondartzan lo egiten zuen Epifanio, zeina izeneko gizon bat zen.",
	"zuzena":"auke1",
	"eranfb1":"Bai, hori da erantzun zuzena.\n-Aspaldi Donostian Kontxako hondartzan lo egiten zuen Epifanio izeneko gizon bat bizi zen.-.",
	"eranfb2":"Ez da zuzena.\n-Aspaldi Donostian Kontxako hondartzan lo egiten zuen Epifanio izeneko gizon bat bizi zen.- da zuzena.",
	"eranfb3":"Ez da zuzena.\n-Aspaldi Donostian Kontxako hondartzan lo egiten zuen Epifanio izeneko gizon bat bizi zen.- da zuzena."},
		//......28
	{"galdera":"Las puertas que dan al río no se pueden abrir.",
	"auke1":"Ateak ematen dutela ibaira ezin dira ireki.","auke2":"Ateak nola ematen duten ibaira ezin dira ireki.","auke3":"Erreka aldera jotzen duten ateak ezin dira ireki.",
	"zuzena":"auke3",
	"eranfb1":"Ez da zuzena.\n-Erreka aldera jotzen duten ateak ezin dira ireki.- da zuzena.",
	"eranfb2":"Ez da zuzena.\n-Erreka aldera jotzen duten ateak ezin dira ireki.- da zuzena.",
	"eranfb3":"Bai, hori da erantzun zuzena:\n-Erreka aldera jotzen duten ateak ezin dira ireki.-"},
		//......29
	{"galdera":"Acaba de terminar el consejo de ministros en el cual se ha decidido subir las pensiones un quince por ciento.",
	"auke1":"Bukatu berria da ministro kontseilua, zeinetan pentsioak ehuneko hamabost igotzea erabaki dute.","auke2":"Amaitu berria da ministro kontseilua, non erabaki da igotzea pentsioak ehuneko hamabost.","auke3":"Bukatu berria da ministro kontseilua, zeinetan pentsioak ehuneko hamabost igotzea erabaki baita.",
	"zuzena":"auke3",
	"eranfb1":"Ez da zuzena. \n-Bukatu berria da ministro kontseilua, zeinetan pentsioak ehuneko hamabost igotzea erabaki baita.- da zuzena. ",
	"eranfb2":"Ez da zuzena. \n-Bukatu berria da ministro kontseilua, zeinetan pentsioak ehuneko hamabost igotzea erabaki baita.- da zuzena. ",
	"eranfb3":"Bai, hori da erantzun zuzena:\n-Bukatu berria da ministro kontseilua, zeinetan pentsioak ehuneko hamabost igotzea erabaki baita.-"},
		//......30
	{"galdera":"Esconde esas botellas que están rayadas.",
	"auke1":"Ezkutatu horiek botilak zeren daude urraturik.","auke2":"Ezkutatu urratuta dauden botila horiek.","auke3":"Ezkutatu horiek botilak daudelako urraturik.",
	"zuzena":"auke2",
	"eranfb1":"Ez da zuzena. \n-Ezkutatu urratuta dauden botila horiek.- da zuzena.",
	"eranfb2":"Bai, hori da erantzun zuzena: \n-Ezkutatu urratuta dauden botila horiek.-",
	"eranfb3":"Ez da zuzena. \n-Ezkutatu urratuta dauden botila horiek.- da zuzena."},
			//......31
	{"galdera":"El hombre que va vestido de verde es mi hermano.",
	"auke1":"Gizona zeina doa jantzita berdearekin da nire anaia.","auke2":"Berdez jantzita doan gizona nire anaia da.","auke3":"Berdez jantzitako gizona nire anaia da.",
	"zuzena":"auke2",
	"eranfb1":"Ez da zuzena. –Berdez jantzita doan gizona nire anaia da.- da zuzena.",
	"eranfb2":"Bai, hori da erantzun zuzena: –Berdez jantzita doan gizona nire anaia da.-",
	"eranfb3":"Ez da zuzena. –Berdez jantzita doan gizona nire anaia da.- di zuzena."},
	] };
	
	return galdesorta;
}
